### ISSUE TITLE
Fail to use ZestRouter: 'Controller class A not found'

### ISSUE THREAD

**Issue by baoc75** [Lablnet/ZestRouter#2]
Hi @lablnet,
I'm very appreciate your work, as it extends the framework and it helps me alot. But now, when I create a Test Controller like the one in example.
And then make a route like this: 
`$router->add('', 'test@index', 'GET');`
It throw this error: Controller class Test not found

**Comment by baoc75** [comment]
Cool I see that you have built a Zest framework :D

**Comment by lablnet** [comment]
@baoc75  I am really sorry you faced the issue `Controller class A not found`

you need to make sure two things.
### First 
if the project route is not the home directory then make sure you have to edit the .htaccess file which distributed with the project
just for instance i am running the example form `router` directory so in my case it will be 
```
# Uncomment the following line if your public folder isn't the web server's root
RewriteBase /router/example/
```
here above the first router is the parent directory of project, and second is like public directory, where the `index.php` file locate.
### second
Do you auto load your App directory by composer? if not you have to update the `composer.json` file 
On line no 15 hit enter key, in my case it become
```json
"psr-4": {
             "Lablnet\\": "src/",
             "App\\": "example/App/"
        }
```
after you save the file make sure you run 
```composer dump-autoload``` and the location `example/App` can be different in your case.


Thanks, hope these one of them step would works for you.
Looking forward to hear from you.

**Comment by lablnet** [comment]
> Cool I see that you have built a Zest framework :D

yes but it still is beta, coz database layer etc still need to work on.

**Comment by baoc75** [comment]
The first issue:
If my public folder like this: root/project/public
Then the configuration should be:
RewriteBase /project/
or RewriteBase /project/public/ ?
I've tried both but it still show error that the Controller is not found

About the second issue, I've installed ZestRouter with Composer.
Thank you!

**Comment by lablnet** [comment]
> The first issue:
> If my public folder like this: root/project/public
> Then the configuration should be:
> RewriteBase /project/
> or RewriteBase /project/public/ ?
> I've tried both but it still show error that the Controller is not found
> 


Could you please show me your `composer.json` file 
secondly, if `root` is directory then you have to prepend that too in your `htaccess` file,  it will become something like `root//project/public/`

Thanks.

**Comment by lablnet** [comment]
{Update}

Even when you install via `composer` it does not auto load your controller directory, because it does now know where you will going to place.
